name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # or your production branch
  pull_request:
    branches:
      - main  # or your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm nx run applaudify:build --configuration=production

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'applaudify'
          directory: './dist/apps/applaudify'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
